# 生成器
【小城贝尔】

方法名前一星号，执行创建迭代到。

配合劫停标志号，后边给值迭代到。

返回数据有它号，遭遇迭代终止到。

还是下一方法号，不同传参劫停到。

首次传参无人号，传参劫杀赋值到。

还有方法返回号，迭代最后传参到。

还抛方法异常号，迭代标志错误到。


## 方法名前一星号，执行创建迭代到。
    生成器语法
    function *name(){

    }
    name();
    当方法执行返回的是一个生成器对象（其实就相当于迭代器）
    然后这个对象也是可以迭代的
## 配合劫停标志号，后边给值迭代到。
    在生成器函数中配合 yield关键字
    每调用一次生成器的next();方法都执行到一个yield关键字的地方停止等待下一次再次调用next方法
    并且将会将 yield后边的数据封装成一个对象{value:"yield值",done:"如果后续还有yield那么就是false"} 返回
## 返回数据有它号，遭遇迭代终止到。
    如果其中有 return 关键字 那么遇到即迭代完毕
    到达迭代最终状态再次调用next();方法返回的对象value 就是 undefined done 是 true
    如果 return xxx;后边有值就是 返回对象的value 值
## 还是下一方法号，不同传参劫停到。
    生成器方法 next(); 和迭代器一样只是这个可以传参数
    传入的参数可以作为 yield的返回值
```js
         // 生成器
        function* made() {
            console.log("我是调用 next()第一个执行的语句");
            yield 3;
            return "遇到我就到最终状态";
            yield 4;
        }
        let m = made();
        //我是调用 next()第一个执行的语句
        console.log(m.next()); //{value: 3, done: false}
        console.log(m.next()); //{value: "遇到我就到最终状态", done: true}
        console.log(m.next()); //{value: undefined, done: true}
```
## 首次传参无人号，传参劫杀赋值到。
    由于传入的参数 是传递给处于最近激活状态的yield关键字
    第一次调用 next("参数");还么有激活的所以第一次传入参数没用
```js
  // 生成器
        function* made() {
            console.log("我是调用 next()第一个执行的语句");
            let mess = yield 3;
            console.log(mess);
            //next方法传入的参数第一没用 但是我是第二次 哈哈 那么一定是第一个yield接待我
            yield 4;
        }
        let m = made();
        //调用next方法传入参数
        m.next("next方法传入的参数第一没用");
        m.next("next方法传入的参数第一没用 但是我是第二次 哈哈 那么一定是第一个yield接待我");

```
## 还有方法返回号，迭代最后传参到。
    return();直接打到最终状态 和执行时 遇到 return 一样
```js
          // 生成器
        function* made() {
            console.log("我是调用 next()第一个执行的语句");
            let mess = yield 3;
            console.log(mess);
            //return 方法传的参数做 value了 我接收不到
            yield 4;
            yield "楼上的千万别 调用 return()方法";
        }
        let m = made();
        //调用next方法传入参数
        m.next("next方法传入的参数第一没用");
        let re = m.return("此法一出立即结束");
        console.log(re); //{value: "此法一出立即结束", done: true}
```
## 还抛方法异常号，迭代标志错误到。
    throw(new Erro("erro message"));
    调用这个方法会让最近的 yield被激活的表达式位置报错
```js
         // 生成器
        function* made() {
            console.log("我是调用 next()第一个执行的语句");
            let mess = yield 3; //外边的没事调用啥 throw方法搞得我都报错了
            yield 4;
            yield "楼上的千万别 调用 return()方法";
        }
        let m = made();
        //调用next方法传入参数
        m.next("next方法传入的参数第一没用");
        let thr = m.throw("此法一出立即报错");
```